services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=database-1.czew08qiqixz.ap-south-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Ardur311012
      - DB_DATABASE=ocr_database
      - DB_TABLENAME=users
      - DB_EMPLOYEE_DETAILS_TABLENAME=employee_details
      - DB_TIMESHEET_TABLENAME=timesheet
      - DB_ATTENDANCE_TABLENAME=attendance
      - DB_LEAVE_REQUESTS_TABLENAME=leave_requests
      - JWT_SECRET=3a8da80f20f9bc6c1525466131e168ef4eecdf33237285632bce79350731aee45d4719ec38c46d22cdb57d39bec5081909cb85a84b01d4f567b1388e94f0a6c5
      - EMAIL_USER=adiraj3110@gmail.com
      - EMAIL_PASS=xooc krei pkkf iozx
    networks:
      - app-network
    depends_on:
      - frontend
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
