name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker images
        run: |
          docker build -t bharti153/frontend:latest ./frontend
          docker build -t bharti153/backend:latest ./backend
      
      - name: Push Docker images to Docker Hub
        run: |
          docker push bharti153/frontend:latest
          docker push bharti153/backend:latest
      
      - name: Deploy to AWS Elastic Beanstalk
        uses: aws-actions/elastic-beanstalk-deploy-action@v1
        with:
          application-name: ardurtech
          environment-name: Ardurtech-env
          version-label: ${{ github.sha }}
          region: ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
